### ISSUE TITLE
v2024.7.23 returns error on start on Python

### ISSUE THREAD

**Issue by DannyC27-git** [tonywagner/plugin.video.mlbserver#13]
The blocking error returned is the following:

C:\Users\plugin.video.mlbserver\resources\lib\account.py:436: SyntaxWarning: invalid escape sequence '\S'
  content = re.sub(r"^((?:#EXT-X-STREAM-INF:BANDWIDTH=)[\d]+(?:,AVERAGE-BANDWIDTH=)[\d]+(?:,CODECS=\"avc1.)[a-z0-9]+(?:,mp4a.40.2\",RESOLUTION=)[\d]+[x](?!" + resolution + ")[\S]+[\n][\S]+[\n])", r"", content, flags=re.M)
Traceback (most recent call last):
  File "C:\Users\plugin.video.mlbserver\service.py", line 4, in <module>
    Server()
  File "C:\Users\plugin.video.mlbserver\resources\lib\server.py", line 169, in __init__
    server = ThreadedHTTPServer()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plugin.video.mlbserver\resources\lib\server.py", line 146, in __init__
    self.utils.server_init()
  File "C:\Users\plugin.video.mlbserver\resources\lib\utils.py", line 96, in server_init
    self.DATABASE_CONNECTION = sqlite3.connect(self.DATABASE_FILE + '?mode=rw', uri=True, check_same_thread=False)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

**Comment by tonywagner** [comment]
The syntax warning is fixed in the latest update (2024.7.24.1). Let me know if the problem continues.

**Comment by DannyC27-git** [comment]
Still returning the same error! I have made sure to delete all files and use all new ones but it still cannot start. Last working version for me was July 22nd's on Python.

**Comment by DannyC27-git** [comment]
It is Python version 3.12.4

The complete log when starting mlbserver is as follows:

C:\Users\>python plugin.video.mlbserver/service.py
Traceback (most recent call last):
  File "C:\Users\plugin.video.mlbserver\service.py", line 4, in <module>
    Server()
  File "C:\Users\plugin.video.mlbserver\resources\lib\server.py", line 169, in __init__
    server = ThreadedHTTPServer()
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plugin.video.mlbserver\resources\lib\server.py", line 146, in __init__
    self.utils.server_init()
  File "C:\Users\plugin.video.mlbserver\resources\lib\utils.py", line 96, in server_init
    self.DATABASE_CONNECTION = sqlite3.connect(self.DATABASE_FILE + '?mode=rw', uri=True, check_same_thread=False)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

**Comment by jtut1731** [comment]
@DannyC27-git,
Do you have a utility for Windows (like https://sqlitebrowser.org/) that can open sqlite3 databases? I might suspect that either something else has the database opened, the permissions on the file are preventing the plugin from opening the file for read/write, or the file is corrupt. If opening the database with the utility doesn't provide any clues, you might try deleting the files from the data folder. (I am running on a mac)

**Comment by tonywagner** [comment]
This should be fixed with https://github.com/tonywagner/plugin.video.mlbserver/commit/687e4b9995c5782584230e67400de5d9c175f28d
